backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "categories"
    label: "Kategorier"
    extension: "json"
    folder: "src/data/categories"
    create: false
    delete: false
    fields:    
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: image}
      - {label: SubCategories, name: subCategories, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}, {label: "Image", name: "image", widget: image},{label: "Video", name: "video", required: false, widget: "string"},{label: "Services", name: "services", widget: "relation", collection: "services", search_fields: ["title", "category"], value_field: "title",multiple: true,display_fields: ["title"]}]} 

  - label: Services
    name: services
    extension: "json"
    folder: "src/data/services"
    create: false
    delete: false
    view_filters:
      - label: "Kategori"
        field: category
        pattern: 'Ansikte'
    fields:          
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", required: false, widget: image}
      - {label: "Video", name: "video", required: false, widget: "string"}
      - {label: Info, name: info ,widget: list,fields: [{label: "Title",name: "title", widget: "string"}, {label: "Text",name: "text", widget: "text"}]} 
  

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}    
          - {label: Image, name: image, widget: image}
          - {label: Description, name: description, widget: text}   
          - {label: "Features", name: "features", widget: "relation", collection: "services", search_fields: ["title", "category"], value_field: "title",multiple: true,display_fields: ["title"]}
          - {label: Image2, name: image2, widget: image}
          - {label: Image3, name: image3, widget: image}
          - {label: Portrait, name: portrait, widget: image}
          - {label: About, name: about, widget: text}   

           
      - file: "src/pages/om/index.md"
        label: "Om"
        name: "om"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: Image, name: image, widget: image}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/behandlingar/index.md"
        label: "Behandlingar"
        name: "behandlingar"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "service-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
      - file: "src/pages/nyhetsbrev/index.md"
        label: "Medlem"
        name: "medlem"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "member-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Body", name: "body", widget: "markdown"}
        
