backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "categories"
    label: "Kategorier"
    extension: "json"
    folder: "src/data/categories"
    create: true
    delete: false
    fields:    
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: image}
      - {label: Info, name: info, widget: list, fields: [{label: Title, name: title, widget: string},{label: "Body", name: "body", widget: "markdown"}]} 
      - {label: "Services", name: "services", widget: list, fields: [{label: Title, name: title, widget: hidden}]}
  - label: Services
    name: services
    extension: "json"
    file: "src/data/Services/services.json"
    create: true
    delete: false
    fields:          
      - {label: "Title", name: "title", widget: "text"}
      - {label: "Category", name: "category", widget: text}
     
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: hidden}   
          - {label: Subtitle, name: subtitle, widget: hidden}     
          - {label: Image, name: image, widget: image}
          - {label: Body, name: body, widget: markdown}   
          - {label: "Features", name: "features", widget: "relation", collection: "services", search_fields: ["title", "category"], value_field: "title",multiple: true,display_fields: ["title"]}       
      - file: "src/pages/om/index.md"
        label: "Om"
        name: "om"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: Image, name: image, widget: image}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/metod/index.md"
        label: "Metod"
        name: "metod"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "method-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: Image, name: image, widget: image}
          - {label: "Body", name: "body", widget: "markdown"}    
      - file: "src/pages/behandlingar/index.md"
        label: "Behandlingar"
        name: "behandlingar"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "service-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
      - file: "src/pages/nyhetsbrev/index.md"
        label: "Medlem"
        name: "medlem"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "member-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Body", name: "body", widget: "markdown"}
        
